name: Pipeline de CI/CD Java com Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout do código
      uses: actions/checkout@v4

    - name: 2. Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: 3. Build com Maven
      run: mvn -B package --file pom.xml -DskipTests # Adicionado -DskipTests para não rodar testes aqui

    - name: 4. Rodar Testes com Maven
      run: mvn test
